import Head from 'next/head';
import { useState } from 'react';
import LoadUserData from '../Components/LoadUserData';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [showButton, setShowButton] = useState(false);

  const handleShowDataButton = () => {
    showButton?setShowButton(false):setShowButton(true);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Friends Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello, Friends ...</h1>
        {
          showButton?<button onClick={handleShowDataButton} className={styles.buttonStyle}>Hide Data</button>:<button onClick={handleShowDataButton} className={styles.buttonStyle}>Load Data</button>
        }
        
        {showButton && <LoadUserData />}
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
